### ISSUE TITLE
Getting started doc

### ISSUE THREAD

**Issue by cratuki** [trunkmaster/nextspace#18]
Appreciate that you are currently focused on this as a personal project, but are open to patches. Love the aim of the project. It is simple and valuable: something equivalent to the pre-Rhapsody GUI, as it was.

The workspace project looks like an area where you have lots of small batches of straightforward but fiddly work. Expect this to be an area where you could get support from a community, to allow you to focus on concerns requiring more focus (e.g. structuring frameworks). 

To get a community going, this project could use a Getting Started doc. It would cover these items,

* Setting up an environment.

* Building the components.

* Running it, as far as possible in its current state.

I have made a first-pass at this, will attach as a comment to this post.

**Comment by cratuki** [comment]
* Getting started

1. Install a recent debian linux.

2. Install the following packages (at least),

build-essential
gcc
make
gnustep
gnustep-base-common
gnustep-base-doc
gnustep-base-examples
gnustep-base-runtime
gnustep-common
gnustep-core-devel
gnustep-core-doc
gnustep-gui-common
gnustep-gui-doc
gnustep-gui-runtime
gnustep-icons
gnustep-make
gnustep-make-doc
libmagic-dev
libxcb-xkb-dev
libx11-dev
pkg-config
xorg

(reckon there are some others)

3. Build the frameworks

I am currently stuck on this. I am running make from within Frameworks and getting errors like this, "NXKeyboard.m:141:11: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode"


4. Change your environment variables to reference Frameworks

xxx how to do this


5. Build the applications

xxx how to do this

**Comment by trunkmaster** [comment]
Thank you for your interest. Workspace is a next application I've planned to focus on after Preferences. Perhaps I'll do switch between those two quite often.

I am fully agree with you about documentation. That's why I've started a while ago developer notes here at "Wiki" section. Also I've made a placeholder named "Build and install". This is the next step when I'll decide project are ready for community attention and help.

Some comments about your "Getting started" proposal:
1. I use CentOS as Linux platform. Do you want to create doc for Debian?
2. My initial goal was to create ready to install RPM packages for CentOS. There are some at "Releases" page here on github. Note that I've done some patching to GNUstep libraries. This is not good idea to install vanilla GNUstep libraries for now. I plan to push upstream as soon as NEXTSPACE 1.0 will be completed.
3. I use 'clang' compiler. Do you use 'gcc'?

In general to join development you need:
1. CentOS 7 (virtual machine is OK)
2. Install packages listed here https://github.com/trunkmaster/nextspace/releases
3. Fetch sources from github
4. Install devel packages (Build-Requires) listed in 'nextspace-frameworks.spec' inside Frameworks subdir
5. Build frameworks (make; make install)
6. Install devel packages (Build-Requires) listed in 'nextspace-desktop.spec' inside Applications subdir
7. Build applications (make; make install)
8. Start login panel application with 'systemctl start loginwindow'
9. Done!

**Comment by cratuki** [comment]
Thanks for these configuration notes. I use virtualbox. CentOS and clang are easy for me.

"Do you want to create doc for Debian?"

The first step for me is to get something that works. I will attempt to copy what you havedone. If this works, it should be easy for me to write build instructions for other platforms later.

**Comment by trunkmaster** [comment]
Great. I'll copy those simple instructions to "Build and install" Wiki page as first version. 

Actually I want to make start page more lightweight by moving some info to Wiki.

**Comment by trunkmaster** [comment]
@cratuki, did you see doc? Does this issue can be considered as closed?

**Comment by trunkmaster** [comment]
No response from @cratuki. Closing issue. Discussion related to the wiki article conitnues in issue #20.
