### ISSUE TITLE
open terminal from current selection

### ISSUE THREAD

**Issue by onflapp** [trunkmaster/nextspace#308]
It would be useful to be able to open Workspace's selected path in Terminal.

Proposed solution: expose current selection using standard services.
User can then use Terminal's "Open shell here" or setup custom service.

Implementation: https://github.com/trunkmaster/nextspace/pull/307

**Comment by trunkmaster** [comment]
@onflapp actually Workspace expose selected path or files selection through pasteboard. There are several ways to have opened Terminal window with selected directory:
1. Drag directory icon from File Viewer's Path View and drop into Terminal window. You'll get directory path pasted into Terminal shell's command line.
2. Create service in Terminal through "Info -> Terminal Services" menu item with `cd %s` command line.

I've just noticed that Services behaves strange: all items always grayed out. Need to find out what the reason is.

**Comment by BertrandDekoninck** [comment]
GWorkspace has this functionnality, it's a menuentry (in the "Tools" submenu ?) and a shortcut ("#t"). I often use this shortcut to open a terminal at the current location with. Can a service be called by a shortcut ? If not, GWorkspace implementation looks better to me.

**Comment by onflapp** [comment]
@BertrandDekoninck the service menu allows you to customize how you open the terminal.
I guess, that Workspace.app could have the menuentry in the "Tools", which will call the first service that it finds with "Open in Terminal" or something along those lines.

I would actually prefer to use "menu shortcuts" in the preferences (not implemented yet). Which would allow you to assign any shortcut to any menu in any app. You could then assign #t (or whatever) to the services menu entry.

**Comment by trunkmaster** [comment]
@BertrandDekoninck "Services" concept imply ability to create service and assign shortcut to it. Terminal application has "Terminal Services" panel (Info->Terminal Services) where you can create service "New Here" ant assign 't' (Cmd+t) to it. Proposed PR #307 by @onflapp just fixes Services functionality in Workspace (I suppose its mechanics was changed in GNUstep since 0.25.0 release).

I don't like the idea to hardcode inter-application intergration. "Services" approach is more flexible to me.

**Comment by trunkmaster** [comment]
@onflapp I think this issue can be closed since PR #307 was merged.
