### ISSUE TITLE
Terminal "Shell | Run Command..."

### ISSUE THREAD

**Issue by trunkmaster** [trunkmaster/nextspace#76]
Terminal Implement "Shell>Run Command..." menu item.
Do we need it? Workspace already has "Launcher" with  completion and history...

**Comment by zeroheure** [comment]
When Apple launched MacOSX, a MacOS expert wrote something about MacOS Classic's ergonomics. He noted that users knew allways how to do something because they were only  _one way_ to do it (and because the places (or menu) for the "things" were carefuly choosen).
He predicted that MacOSX won't be as easy than MacOS Classic for years, because it takes very long time to eliminate duplicate ways to do something. 

So, to answer your question, please do not duplicate, command launcher. Even if Terminal is for power users, I think it is better to add it later if really needed that to find a way to remove it if it confuse users.

**Comment by armm77** [comment]
I agree with @zeroheure comment.

**Comment by trunkmaster** [comment]
@zeroheure I've created this issue to open a discussion (NeXT's Terminal has this menu command). NeXT's Workspace manager doesn't have "Launcher..." menu item. Thank you very much for clear argument! I agree.

Closing this issue as: duplicated to the Workspace's Launcher.
